# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCScores', '0004_auto_20180607_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_1_score',
            field=models.IntegerField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_2_score',
            field=models.IntegerField(null=True, blank=True),
        ),
    ]

