# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCScores', '0005_auto_20180609_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_1_score',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_2_score',
            field=models.IntegerField(default='0'),
        ),
    ]
