# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCScores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='afgdf',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
