# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCScores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='scored',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_1_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_2_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
