# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCScores', '0002_userscore_afgdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscore',
            name='afgdf',
        ),
    ]
