# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCScores', '0003_auto_20180607_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='date',
        ),
        migrations.AlterField(
            model_name='match',
            name='day',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
