# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WCScores', '0004_scoreboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='draw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='WCScores.Team'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='perfect',
            field=models.BooleanField(default=False),
        ),
    ]
