# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCScores', '0005_auto_20180612_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoreboard',
            old_name='justwinner',
            new_name='perfect',
        ),
        migrations.RenameField(
            model_name='scoreboard',
            old_name='perfectlyscored',
            new_name='scored',
        ),
    ]
