# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCScores', '0007_auto_20180609_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_1_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_2_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
